# Generated by Django 5.2.8 on 2025-11-19 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('descripcion_tecnica', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_licencia', models.CharField(choices=[('perpetua', 'Licencia Perpetua'), ('anual', 'Licencia Anual'), ('mensual', 'Licencia Mensual'), ('trial', 'Versión de Prueba')], default='perpetua', max_length=20)),
                ('version_actual', models.CharField(default='1.0.0', max_length=20)),
                ('archivo_descarga', models.FileField(blank=True, null=True, upload_to='software/')),
                ('requisitos_sistema', models.TextField(blank=True, null=True)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('captura1', models.ImageField(blank=True, null=True, upload_to='productos/capturas/')),
                ('captura2', models.ImageField(blank=True, null=True, upload_to='productos/capturas/')),
                ('captura3', models.ImageField(blank=True, null=True, upload_to='productos/capturas/')),
                ('stock', models.IntegerField(default=999)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='api.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-destacado', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_servicio', models.CharField(choices=[('web', 'Desarrollo Web'), ('ia', 'Agente de IA'), ('chatbot', 'Chatbot'), ('ml', 'Machine Learning'), ('mobile', 'App Móvil'), ('iot', 'Sistema IoT'), ('redes', 'Solución de Redes'), ('automatizacion', 'Automatización'), ('consultoria', 'Consultoría')], max_length=20)),
                ('precio_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cotizacion_dinamica', models.BooleanField(default=False)),
                ('tiempo_estimado_dias', models.IntegerField(default=30)),
                ('requisitos_cliente', models.TextField(help_text='Información requerida del cliente')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='servicios/')),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='api.categoria')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-destacado', '-fecha_creacion'],
            },
        ),
    ]
